### ISSUE TITLE
ori_4015imgs_weights.hdf5

### ISSUE THREAD

**Issue by sam2099** [asingh33/CNNGestureRecognizer#1]
hello
Thank you for codes.

where is ori_4015imgs_weights.hdf5?

**Comment by asingh33** [comment]
Hi,
Yeah I couldn't upload those weighted files due to file size limitation on github. Thats why I provided the training images I used to generate ori_4015imgs_weights.hdf5 (or rename it accordingly). All you need to do is train the model as an initial step and save the hdf5 file. Then you can use it for predictions.

**Comment by asingh33** [comment]
I searched more on how to upload large files on github. There is a way using LFS repo on github, so I will try to learn to set it up and upload the weight file. Reopening this issue for tracking purpose.

**Comment by asingh33** [comment]
Ok checked in. Thanks for opening the issue which pushed me to learn more about git large file storage :)

**Comment by sam2099** [comment]
aha, thank you very much

**Comment by JarveeLee** [comment]
I still could not get the model weights file. After downloading,  ori_4015imgs_weights.hdf5 is just 134B. 
Any help? 
Thanks

**Comment by asingh33** [comment]
Hey JarveeLee I have reopened the your issue. Its due to my GIT LFS quota getting over. I need to purchase their plan to increase the quota. Will do and update.
