### ISSUE TITLE
Why different hdf5 model file for macos and win? 

### ISSUE THREAD

**Issue by BeckZhang** [asingh33/CNNGestureRecognizer#61]
I think the model should be the same, regarding the training data set (in path imgfolder_b), in spite of the OS.
So, what's the difference between models for mac and win?

**Comment by asingh33** [comment]
Hey,
Yes that is what I would expect as well. However, for some reason I was seeing plenty of precision difference when I used my MacOS based pretrained model on Windows. 
I had to retrain the model on Windows and it worked with similar precision after that.
This was a surprising observation and couldn't dig into the actual root cause due to time limitation on my end.

**Comment by BeckZhang** [comment]
Maybe you could compare the input data, for seeking the os difference. Just FYI.

**Comment by asingh33** [comment]
I cant anymore. Dont have windows platform to try on now.
